### PR TITLE
pref: Improved implementation of tinybench

### PR DESCRIPTION
**Pull request by Dunqing**
I think here do not need to run optimizations.

### CODE REVIEW

**Comment by adriencaccia** [comment]
Hey @Dunqing,

We run optimizations to have a more consistent result in the benchmarks. Removing them will result in flakier benchmarks, which we do not want.
Why do you think we do not need them?

Another thing, you removed the use of `__codspeed_root_frame__`, which is essential for profiling to work. So we want to keep it.

**Comment by Dunqing** [comment]
> We run optimizations to have a more consistent result in the benchmarks. Removing them will result in flakier benchmarks, which we do not want. Why do you think we do not need them? Maybe there is something about your use case?

In `vitest`, the `warm` function is executed by default. warm` is similar to `optimizedFunction`. In `Tinybench`, `warm` is not executed by default. But usually the user writing the test will run `warm` first. Therefore, I don't think we need to run optimization, it should be up to the user to decide.

> 
> Another thing, you removed the use of `__codspeed_root_frame__`, which is essential for profiling to work. So we want to keep it.

Ok, I will keep it

**Comment by adriencaccia** [comment]
> In `vitest`, the `warm` function is executed by default. `warm` is similar to `optimizedFunction`. In `Tinybench`, `warm` is not executed by default. But usually the user writing the test will run `warm` first. Therefore, I don't think we need to run optimization, it should be up to the user to decide.

I agree with you, we do not need to run the optimization; an expert user could decide to run it. But at the moment we think that running the optimization is a more sensible default than not running it.

What I would propose is having a config parameter `runOptimizations = true` in the `withCodSpeed` function, with a JSDoc comment that states that setting it to `false` can result in flakier benchmarks.
Depending on this parameter, we would run or not the optimization.

What do you think?

**Comment by Dunqing** [comment]
Sorry, I just realized that the original processing was correct and that this PR makes no sense anymore I will close it.

**Pull request closed without merging**
